//! Cedar ABAC policy engine wrapper.
//!
//! ABAC is used as the final contextual filter at the edge; ReBAC remains the
//! source of structural truth.

use std::collections::HashMap;
use std::sync::Arc;

use arc_swap::ArcSwapOption;
use cedar_policy::{
    Authorizer, Context, Decision, Entities, EntityUid, PolicySet, Request, RestrictedExpression,
};

use crate::types::{AuthError, CedarContext, CedarContextBuilder, CedarValueRef};

/// An Attribute-Based Access Control (ABAC) engine driven by the Cedar policy language.
///
/// This engine provides dynamic, contextual authorization checks at the application edge.
/// It works alongside a structural ReBAC layer, consuming downstream properties
/// (such as structural allowance verdicts, IP addresses, or temporal scopes) to output
/// deterministic access decisions. It supports thread-safe runtime policy hot-swapping via `ArcSwap`.
pub struct AbacEngine {
    policies: ArcSwapOption<PolicySet>,
    authorizer: Authorizer,
}

impl AbacEngine {
    /// Creates a new `AbacEngine` instance initialized with the provided Cedar policies.
    ///
    /// # Arguments
    ///
    /// * `initial_policies_dsl` - An optional string slice containing raw Cedar policy syntax definitions.
    ///   If `None`, the engine initializes with ABAC validation disabled (passthrough mode).
    ///
    /// # Errors
    ///
    /// Returns an `AuthError` if the provided policy syntax is invalid or fails static validation checks.
    pub fn new(initial_policies_dsl: Option<&str>) -> Result<Self, AuthError> {
        let policies = match initial_policies_dsl {
            Some(dsl) => Some(Arc::new(parse_policies(dsl)?)),
            None => None,
        };

        Ok(Self {
            policies: ArcSwapOption::from(policies),
            authorizer: Authorizer::new(),
        })
    }

    /// Hot-swaps or updates the internal Cedar policies at runtime across all threads.
    ///
    /// # Arguments
    ///
    /// * `new_policies_dsl` - An optional string slice containing the replacement Cedar policy DSL.
    ///   Passing `None` completely disables active ABAC evaluations.
    ///
    /// # Errors
    ///
    /// Returns an `AuthError` if the newly supplied string fails compilation or contains structural syntax flaws.
    pub fn update_policies(&self, new_policies_dsl: Option<&str>) -> Result<(), AuthError> {
        let next = match new_policies_dsl {
            Some(dsl) => Some(Arc::new(parse_policies(dsl)?)),
            None => None,
        };

        self.policies.store(next);
        Ok(())
    }

    /// Evaluates incoming attributes against the active Cedar policies to determine authorization.
    ///
    /// If the ABAC layer is completely disabled (no policies loaded), this method bypasses
    /// the Cedar authorizer entirely and immediately returns the structural evaluation fallback value.
    ///
    /// # Arguments
    ///
    /// * `is_structural_allowed` - The explicit pass/fail authorization result generated by the upstream ReBAC layer.
    /// * `user_id` - The unique identifier of the requesting user principal.
    /// * `action` - The specific action moniker string being attempted.
    /// * `resource_type` - The domain category or namespace of the targeted resource.
    /// * `resource_id` - The unique instance identity key representing the targeted resource.
    /// * `ctx` - Optional strong or dynamic context container properties containing extra validation attributes.
    ///
    /// # Errors
    ///
    /// Returns an `AuthError` if:
    /// - Parsed entities (`user_id`, `action`, `resource_id`) fail formatting or identifier generation rules.
    /// - Building the concrete Cedar execution context or parsing expression types fails.
    pub fn is_allowed<'a, C>(
        &self,
        is_structural_allowed: bool,
        user_id: &str,
        action: &str,
        resource_type: &str,
        resource_id: &str,
        ctx: Option<&'a C>,
    ) -> Result<bool, AuthError>
    where
        C: CedarContext<'a>,
    {
        let Some(policies) = self.policies.load_full() else {
            return Ok(is_structural_allowed);
        };

        let principal = parse_uid("User", user_id)?;
        let action_uid = parse_uid("Action", action)?;
        let resource = parse_uid(resource_type, resource_id)?;

        // Collect dynamic context pairs first, then convert to Cedar types in one pass.
        let mut builder = CedarContextBuilder::with_capacity(8);
        builder.insert_bool("is_structural_allowed", is_structural_allowed);

        if let Some(ctx) = ctx {
            ctx.write_to(&mut builder)?;
        }

        let cedar_ctx = build_cedar_context(&builder)?;
        let req = Request::new(principal, action_uid, resource, cedar_ctx, None)
            .map_err(AuthError::cedar_eval)?;

        let entities = Entities::empty();
        let resp = self
            .authorizer
            .is_authorized(&req, policies.as_ref(), &entities);

        Ok(matches!(resp.decision(), Decision::Allow))
    }
}

/// Transforms an internal `CedarContextBuilder` into a native Cedar engine `Context` object.
///
/// # Arguments
///
/// * `b` - The target internal context builder structure to transform.
///
/// # Errors
///
/// Returns an `AuthError` if conversion to an engine-compatible context pair fails.
fn build_cedar_context(b: &CedarContextBuilder<'_>) -> Result<Context, AuthError> {
    let mut map: HashMap<String, RestrictedExpression> = HashMap::with_capacity(b.entries.len());

    for (k, v) in b.entries.iter() {
        let expr = match v {
            CedarValueRef::Bool(x) => RestrictedExpression::new_bool(*x),
            CedarValueRef::I64(x) => RestrictedExpression::new_long(*x),
            CedarValueRef::Str(s) => RestrictedExpression::new_string((*s).to_owned()),
        };
        map.insert((*k).to_owned(), expr);
    }

    Context::from_pairs(map).map_err(AuthError::cedar_eval)
}

/// Parses a string slice containing a raw Cedar policy payload into a validated `PolicySet`.
///
/// # Arguments
///
/// * `dsl` - The string slice of policy definitions to parse.
///
/// # Errors
///
/// Returns an `AuthError` if compilation fails due to syntactic syntax syntax errors.
fn parse_policies(dsl: &str) -> Result<PolicySet, AuthError> {
    dsl.parse::<PolicySet>()
        .map_err(AuthError::cedar_validation)
}

/// Assembles a string-formatted entity block and parses it into a valid `EntityUid`.
///
/// # Arguments
///
/// * `entity_type` - The broad namespace segment classification (e.g., "User", "Action").
/// * `entity_id` - The inner unique payload identifier string.
///
/// # Errors
///
/// Returns an `AuthError` if the resulting identifier syntax contains escape sequence conflicts.
fn parse_uid(entity_type: &str, entity_id: &str) -> Result<EntityUid, AuthError> {
    let mut s = String::with_capacity(entity_type.len() + entity_id.len() + 6);
    s.push_str(entity_type);
    s.push_str("::\"");
    s.push_str(entity_id);
    s.push('"');
    s.parse::<EntityUid>().map_err(AuthError::cedar_validation)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{
        cedar_context_map,
        types::{AuthError, CedarContext},
    };

    #[derive(Debug)]
    struct DemoCtx<'a> {
        ip: &'a str,
        hour: i64,
    }

    impl<'a> CedarContext<'a> for DemoCtx<'a> {
        fn write_to(
            &self,
            out: &mut crate::types::CedarContextBuilder<'a>,
        ) -> Result<(), AuthError> {
            cedar_context_map!(out, self, {
                "ip" => str self.ip,
                "hour" => i64 self.hour,
            });
            Ok(())
        }
    }

    #[test]
    fn abac_disabled_passthrough() -> Result<(), AuthError> {
        let engine = AbacEngine::new(None)?;
        let ok = engine.is_allowed::<()>(true, "u1", "read", "entity", "e1", None)?;
        assert!(ok);
        Ok(())
    }

    #[test]
    fn abac_denies_when_policy_requires_structural_true() -> Result<(), AuthError> {
        let policies = r#"
          permit(principal, action, resource)
          when { context.is_structural_allowed == true };
        "#;

        let engine = AbacEngine::new(Some(policies))?;

        let ctx = DemoCtx {
            ip: "203.0.113.10",
            hour: 12,
        };

        let ok = engine.is_allowed(false, "u1", "read", "entity", "e1", Some(&ctx))?;
        assert!(!ok);
        Ok(())
    }
}
